### POST request to create a patient
POST http://0.0.0.0:4000/patients
Content-Type: application/json

{
  "name": "John Doe with billing account",
  "email": "test_billing_account1244@example.com",
  "address": "123 main street",
  "dateOfBirth": "1990-05-23",
  "registeredDate": "2025-08-08"
}
###